(function(){
  const root=document.getElementById('admin-users');
  if(!root)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const atomic=v=>(Number(v||0)/1e8).toFixed(2)+' YERB';
  const when=t=>t?new Date(Number(t)*1000).toLocaleString():'—';
  const ago=t=>{if(!t)return'never';const d=Math.max(0,Math.floor(Date.now()/1000-Number(t)));if(d<60)return d+'s ago';if(d<3600)return Math.floor(d/60)+'m ago';if(d<86400)return Math.floor(d/3600)+'h ago';return Math.floor(d/86400)+'d ago'};
  const hashRate=v=>{v=Number(v||0);if(v>=1e9)return(v/1e9).toFixed(2)+' GH/s';if(v>=1e6)return(v/1e6).toFixed(2)+' MH/s';if(v>=1e3)return(v/1e3).toFixed(2)+' kH/s';return v.toFixed(1)+' H/s'};
  const pct=v=>Number(v||0).toFixed(2)+'%';
  async function api(url,body){const options=body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};const response=await fetch(url,options),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||response.statusText);return data;}
  function metric(label,value,detail=''){return `<div class="admin-user-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong>${detail?`<small>${esc(detail)}</small>`:''}</div>`;}
  function ipList(user){if(!user.ips?.length)return'<div class="muted user-empty-detail">No IP addresses recorded yet.</div>';return user.ips.map(ip=>`<div class="admin-ip"><div><code>${esc(ip.ip_address)}</code> ${ip.banned?'<span class="user-badge user-banned">Banned</span>':''}</div><div class="muted user-small">${esc(ip.country||'Country unavailable')} · ${Number(ip.connection_count||0).toLocaleString()} connection${Number(ip.connection_count||0)===1?'':'s'} · Last seen ${ago(ip.last_seen_at)}</div><button class="user-mini-btn ${ip.banned?'':'danger'}" data-ip="${esc(ip.ip_address)}" data-ban="${ip.banned?'0':'1'}">${ip.banned?'Unban IP':'Ban IP'}</button></div>`).join('');}
  function workerList(user){if(!user.workers?.length)return'<div class="muted user-empty-detail">No workers recorded.</div>';return `<div class="admin-worker-list">${user.workers.map(worker=>`<div><a href="/worker/${encodeURIComponent(worker.id)}" target="_blank"><code>${esc(worker.name)}</code></a><a class="user-export-link" href="/api/admin/export/worker/${encodeURIComponent(worker.id)}.csv">Lifetime CSV ↓</a></div>`).join('')}</div>`;}
  function userCard(user){
    const search=[user.address,user.country,user.country_code,(user.worker_names||[]).join(' '),(user.ips||[]).map(ip=>ip.ip_address).join(' ')].join(' ').toLowerCase(),total=Number(user.accepted_shares||0)+Number(user.rejected_shares||0);
    return `<article class="admin-user-card" data-user-row data-search="${esc(search)}"><div class="admin-user-head"><div class="admin-user-identity"><div class="admin-user-title"><a href="/account/${encodeURIComponent(user.address)}" target="_blank"><code>${esc(user.address)}</code></a></div><div class="muted user-small">Last share ${ago(user.last_share_at)} · ${esc(user.country||'Location unavailable')}</div></div><div class="admin-user-status"><span class="user-badge ${user.enabled?'user-ok':'user-paused'}">Payments ${user.enabled?'active':'held'}</span><span class="user-badge ${user.suspended?'user-suspended':'user-ok'}">Mining ${user.suspended?'suspended':'active'}</span></div></div>
      <div class="admin-user-metrics">${metric('Current hashrate',hashRate(user.hashrate),'recent estimate')}${metric('24h average',hashRate(user.hashrate_24h),'all workers')}${metric('Mature balance',atomic(user.balance_atomic),'available')}${metric('Immature balance',atomic(user.immature_balance_atomic),'awaiting maturity')}${metric('Total paid',atomic(user.total_paid_atomic),'lifetime')}${metric('Workers',Number(user.worker_count||0).toLocaleString(),`${Number(user.active_workers||0).toLocaleString()} active`)}${metric('Accepted',Number(user.accepted_shares||0).toLocaleString(),'lifetime shares')}${metric('Rejected',Number(user.rejected_shares||0).toLocaleString(),`${pct(user.rejection_percent)} reject rate`)}</div>
      <div class="admin-user-actions"><button class="user-control-btn ${user.enabled?'danger':''}" data-payment-address="${esc(user.address)}" data-enabled="${user.enabled?'0':'1'}">${user.enabled?'Hold payments':'Resume payments'}</button><button class="user-control-btn ${user.suspended?'':'danger'}" data-mining-address="${esc(user.address)}" data-suspended="${user.suspended?'0':'1'}">${user.suspended?'Resume mining':'Suspend mining'}</button><a class="admin-user-download" href="/api/admin/export/account/${encodeURIComponent(user.address)}.csv">Account lifetime CSV ↓</a></div>
      <div class="admin-user-details"><details><summary>Workers & exports <span>${Number(user.worker_count||0).toLocaleString()}</span></summary>${workerList(user)}</details><details><summary>Activity details</summary><dl><div><dt>First seen</dt><dd>${when(user.created_at)}</dd></div><div><dt>Last share</dt><dd>${when(user.last_share_at)} (${ago(user.last_share_at)})</dd></div><div><dt>Last payout</dt><dd>${when(user.last_payout_at)}</dd></div><div><dt>Country</dt><dd>${esc(user.country||'Unavailable')}${user.country_code?` (${esc(user.country_code)})`:''}</dd></div><div><dt>Total shares</dt><dd>${total.toLocaleString()}</dd></div><div><dt>Reject rate</dt><dd>${pct(user.rejection_percent)}</dd></div></dl></details><details><summary>Network & IP history <span>${Number(user.ips?.length||0).toLocaleString()}</span></summary>${ipList(user)}</details></div></article>`;
  }
  function bindActions(){
    root.querySelectorAll('[data-payment-address]').forEach(button=>button.onclick=async()=>{const enable=button.dataset.enabled==='1',address=button.dataset.paymentAddress;if(!enable&&!confirm(`Place payments on hold for ${address}?`))return;button.disabled=true;try{await api('/api/admin/users/payment',{address,enabled:enable});await load();}catch(error){alert(error.message);button.disabled=false;}});
    root.querySelectorAll('[data-mining-address]').forEach(button=>button.onclick=async()=>{const suspend=button.dataset.suspended==='1',address=button.dataset.miningAddress;if(suspend&&!confirm(`Suspend mining for ${address}?`))return;button.disabled=true;try{await api('/api/admin/users/mining',{address,suspended:suspend});await load();}catch(error){alert(error.message);button.disabled=false;}});
    root.querySelectorAll('[data-ip]').forEach(button=>button.onclick=async()=>{const ban=button.dataset.ban==='1',ip=button.dataset.ip;if(ban&&!confirm(`Ban ${ip} from connecting to the Stratum pool?`))return;button.disabled=true;try{await api('/api/admin/users/ip-ban',{ip_address:ip,banned:ban});await load();}catch(error){alert(error.message);button.disabled=false;}});
  }
  function render(users){if(!users.length){root.innerHTML='<div class="admin-card muted">No miner users have been recorded yet.</div>';return;}const ordered=[...users].sort((a,b)=>Number(b.active_workers||0)-Number(a.active_workers||0)||Number(b.last_share_at||0)-Number(a.last_share_at||0));root.innerHTML=`<div class="user-toolbar"><input id="admin-user-search" type="search" placeholder="Search address, worker, IP or country"><span class="muted"><strong id="admin-user-visible">${ordered.length.toLocaleString()}</strong> of ${ordered.length.toLocaleString()} users</span></div><div class="admin-user-cards">${ordered.map(userCard).join('')}</div><div id="admin-user-message"></div>`;const search=root.querySelector('#admin-user-search'),visible=root.querySelector('#admin-user-visible');search?.addEventListener('input',()=>{const query=search.value.trim().toLowerCase();let count=0;root.querySelectorAll('[data-user-row]').forEach(card=>{card.hidden=!!query&&!card.dataset.search.includes(query);if(!card.hidden)count++;});visible.textContent=count.toLocaleString();});bindActions();}
  async function load(){root.innerHTML='<div class="admin-card">Loading users…</div>';try{const data=await api('/api/admin/users');render(data.users||[]);}catch(error){root.innerHTML=`<div class="admin-card error">${esc(error.message)}</div>`;}}
  window.loadAdminUsers=load;load();
})();
