(function(){
  'use strict';
  if(location.pathname!=='/') return;

  const RANGES={'1H':{hours:1,bucket:60},'6H':{hours:6,bucket:300},'12H':{hours:12,bucket:300},'24H':{hours:24,bucket:600},'7D':{hours:168,bucket:3600}};
  const STORAGE_KEY='yerbNetworkHashSamplesV4';
  let selected='24H',preload=window.__YERB_HASHRATE_PRELOAD__||null,rendering=false,initialized=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const hashRate=v=>{v=Number(v||0);if(v>=1e9)return(v/1e9).toFixed(2)+' GH/s';if(v>=1e6)return(v/1e6).toFixed(2)+' MH/s';if(v>=1e3)return(v/1e3).toFixed(2)+' kH/s';return v.toFixed(1)+' H/s';};

  function ensureStyles(){
    if(document.getElementById('hashrate-fast-styles'))return;
    const s=document.createElement('style');s.id='hashrate-fast-styles';s.textContent=`
      .combined-hash-grid{grid-template-columns:1fr!important}.combined-hash-card{width:100%}.hash-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap}
      .hash-range{display:flex;gap:7px;flex-wrap:wrap}.hash-range button{background:#24242c;color:#eee;border:1px solid #666b78;border-radius:7px;padding:6px 11px;font-size:11px;font-weight:700;cursor:pointer}.hash-range button.active{background:rgba(101,196,102,.15);border-color:#65c466;color:#e2ffe4}
      .hash-metrics{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:10px;margin:14px 0}.hash-metric{border:1px solid #2d4332;border-radius:9px;padding:11px 13px;background:#141816}.hash-metric span{display:block;color:#9caf9d;font-size:11px}.hash-metric strong{display:block;color:#e9f7ea;font-size:19px;margin-top:3px}.hash-metric small{display:block;color:#829184;font-size:10px;margin-top:3px}
      .combined-chart-wrap{position:relative;margin-top:8px}.combined-hash-chart{width:100%;height:340px;display:block;cursor:crosshair;overflow:visible}.combined-hash-chart .gridline{stroke:#2d2d2d;stroke-width:1}.combined-hash-chart .pool-line{fill:none;stroke:#65c466;stroke-width:2.6;vector-effect:non-scaling-stroke}.combined-hash-chart .network-line{fill:none;stroke:#45a3ff;stroke-width:2.4;vector-effect:non-scaling-stroke}.combined-hash-chart .pool-area{fill:rgba(101,196,102,.11)}.combined-hash-chart .network-area{fill:rgba(69,163,255,.07)}.combined-hash-chart .axis{font-size:10px;fill:#8ea091}.combined-hash-chart .pool-axis{fill:#80d985}.combined-hash-chart .net-axis{fill:#6eb7ff}.combined-hash-chart .block-bar{fill:#e5b94c;opacity:.95}.combined-hash-chart .block-baseline{stroke:#745f25;stroke-width:1}.hash-crosshair{stroke:#8b968d;stroke-width:1;stroke-dasharray:4 4;opacity:0;vector-effect:non-scaling-stroke}
      .combined-hash-tooltip{position:absolute;z-index:9;pointer-events:none;min-width:180px;padding:9px 11px;border:1px solid #35503b;border-radius:8px;background:rgba(9,14,11,.97);font-size:11px;line-height:1.55;color:#e6efe7;transform:translate(-50%,-112%)}
      .hash-legend{display:flex;justify-content:center;gap:22px;flex-wrap:wrap;margin-top:9px;font-size:12px}.hash-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px}.hash-dot.pool{background:#65c466}.hash-dot.net{background:#45a3ff}.hash-dot.blocks{background:#e5b94c;border-radius:2px}.hash-footer{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:8px;color:#718477;font-size:10px}.hash-loading{min-height:340px;display:flex;align-items:center;justify-content:center;color:#819284;font-size:13px}
      @media(max-width:900px){.hash-metrics{grid-template-columns:repeat(2,minmax(130px,1fr))}}@media(max-width:560px){.hash-metrics{grid-template-columns:1fr}.combined-hash-chart{height:300px}}
    `;document.head.appendChild(s);
  }
  function findCard(){const cards=[...document.querySelectorAll('main#app .chart-card')];let c=cards.find(x=>['Pool Hashrate','Network Hash vs Pool Hash'].includes(x.querySelector('h3')?.textContent.trim()));const other=cards.find(x=>['Share Activity','Network vs Pool Hashrate'].includes(x.querySelector('h3')?.textContent.trim()));if(!c&&other)c=other;if(!c)return null;const grid=c.closest('.chart-grid');if(grid){grid.style.gridTemplateColumns='1fr';grid.classList.add('combined-hash-grid');}if(other&&other!==c)other.remove();c.classList.add('combined-hash-card');return c;}
  async function fetchData(range){const r=RANGES[range];if(range==='24H'&&preload){const p=preload;preload=null;try{return await p;}catch(_){return null;}}try{const res=await fetch(`/api/hashrate/chart?hours=${r.hours}&bucket=${r.bucket}`,{cache:'no-store',credentials:'same-origin'});return res.ok?await res.json():null;}catch(_){return null;}}
  function readSamples(){try{const a=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(a)?a:[];}catch(_){return[];}}
  function sampleNetwork(v){const now=Math.floor(Date.now()/1000);let a=readSamples().filter(x=>Number(x.ts)>now-8*86400),last=a[a.length-1];if(!last||now-Number(last.ts)>=60){a.push({ts:now,hashrate:Number(v||0)});if(a.length>12000)a=a.slice(-12000);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(a));}catch(_){}}return a;}
  function networkAt(a,ts,fallback){if(!a.length)return fallback;let best=a[0];for(const x of a)if(Math.abs(Number(x.ts)-ts)<Math.abs(Number(best.ts)-ts))best=x;return Number(best.hashrate||fallback);}
  function stats(v){v=v.filter(Number.isFinite);return v.length?{avg:v.reduce((a,b)=>a+b,0)/v.length,peak:Math.max(...v)}:{avg:0,peak:0};}
  function label(ts){const d=new Date(ts*1000);return selected==='7D'?d.toLocaleDateString([],{month:'short',day:'numeric'}):d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}

  function makeSvg(history,samples,networkNow,blocks){
    const W=1120,H=340,L=72,R=78,T=22,B=46,iw=W-L-R,ih=H-T-B,barH=18;
    const rows=history.map(x=>({ts:Number(x.ts||0),pool:Number(x.hashrate||0),network:networkAt(samples,Number(x.ts||0),networkNow)}));
    const pmax=Math.max(...rows.map(x=>x.pool),1)*1.12,nmax=Math.max(...rows.map(x=>x.network),networkNow,1)*1.12,min=rows[0]?.ts||0,max=rows[rows.length-1]?.ts||min+1;
    const px=ts=>L+(ts-min)/Math.max(1,max-min)*iw,pyP=v=>T+ih-Number(v||0)/pmax*ih,pyN=v=>T+ih-Number(v||0)/nmax*ih;
    const pp=rows.map(r=>`${px(r.ts).toFixed(1)},${pyP(r.pool).toFixed(1)}`).join(' '),np=rows.map(r=>`${px(r.ts).toFixed(1)},${pyN(r.network).toFixed(1)}`).join(' ');
    let grid='';for(let i=0;i<=4;i++){const y=T+ih*i/4;grid+=`<line class="gridline" x1="${L}" y1="${y}" x2="${W-R}" y2="${y}"/><text class="axis pool-axis" x="4" y="${y+4}">${esc(hashRate(pmax*(1-i/4)))}</text><text class="axis net-axis" text-anchor="end" x="${W-4}" y="${y+4}">${esc(hashRate(nmax*(1-i/4)))}</text>`;}
    let labels='';const count=selected==='7D'?7:6;for(let i=0;i<count;i++){const ts=min+(max-min)*i/Math.max(1,count-1),x=px(ts);labels+=`<text class="axis" text-anchor="${i===0?'start':i===count-1?'end':'middle'}" x="${x}" y="${H-10}">${esc(label(ts))}</text>`;}
    const pa=rows.length?`${L},${T+ih} ${pp} ${W-R},${T+ih}`:'',na=rows.length?`${L},${T+ih} ${np} ${W-R},${T+ih}`:'';
    const validBlocks=(blocks||[]).filter(b=>Number(b.submitted_at)>=min&&Number(b.submitted_at)<=max);
    const blockBars=validBlocks.map(b=>{const x=px(Number(b.submitted_at));return `<rect class="block-bar" data-block-height="${esc(b.height)}" x="${(x-2.5).toFixed(1)}" y="${(T+ih-barH).toFixed(1)}" width="5" height="${barH}" rx="1"/>`;}).join('');
    const baseline=validBlocks.length?`<line class="block-baseline" x1="${L}" y1="${T+ih}" x2="${W-R}" y2="${T+ih}"/>`:'';
    return `<div class="combined-chart-wrap"><svg class="combined-hash-chart" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}<polygon class="network-area" points="${na}"/><polygon class="pool-area" points="${pa}"/><polyline class="network-line" points="${np}"/><polyline class="pool-line" points="${pp}"/>${baseline}${blockBars}${labels}<line class="hash-crosshair" x1="0" x2="0" y1="${T}" y2="${T+ih}"/></svg><div class="combined-hash-tooltip" hidden></div></div>`;
  }

  function bind(c,history,samples,networkNow,blocks){
    c.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{if(!RANGES[b.dataset.range]||b.dataset.range===selected)return;selected=b.dataset.range;render(true);});
    const el=c.querySelector('.combined-hash-chart'),tip=c.querySelector('.combined-hash-tooltip'),cross=c.querySelector('.hash-crosshair');if(!el||!tip||!cross||!history.length)return;
    const W=1120,L=72,R=78,min=Number(history[0].ts||0),max=Number(history[history.length-1].ts||min+1),blockList=(blocks||[]).filter(b=>Number(b.submitted_at)>=min&&Number(b.submitted_at)<=max);
    el.onmousemove=e=>{const r=el.getBoundingClientRect(),sx=Math.max(L,Math.min(W-R,(e.clientX-r.left)/r.width*W)),target=min+(max-min)*(sx-L)/(W-L-R);let best=history[0];for(const x of history)if(Math.abs(Number(x.ts)-target)<Math.abs(Number(best.ts)-target))best=x;const pool=Number(best.hashrate||0),net=networkAt(samples,Number(best.ts),networkNow),share=net>0?pool/net*100:0,x=L+(Number(best.ts)-min)/Math.max(1,max-min)*(W-L-R);let nearest=null;for(const b of blockList)if(!nearest||Math.abs(Number(b.submitted_at)-target)<Math.abs(Number(nearest.submitted_at)-target))nearest=b;const threshold=(max-min)*12/(W-L-R);const blockLine=nearest&&Math.abs(Number(nearest.submitted_at)-target)<=threshold?`<br><span style="color:#e5b94c">Pool block #${esc(nearest.height)}</span><br>${esc(new Date(Number(nearest.submitted_at)*1000).toLocaleString())}`:'';cross.setAttribute('x1',x);cross.setAttribute('x2',x);cross.style.opacity='1';tip.hidden=false;tip.innerHTML=`<strong>${esc(new Date(Number(best.ts)*1000).toLocaleString())}</strong><br><span style="color:#80d985">Pool</span>: ${esc(hashRate(pool))}<br><span style="color:#6eb7ff">Network</span>: ${esc(hashRate(net))}<br>Pool share: ${share.toFixed(2)}%${blockLine}`;tip.style.left=`${x/W*100}%`;tip.style.top='58%';};
    el.onmouseleave=()=>{tip.hidden=true;cross.style.opacity='0';};
  }

  async function render(showLoading=false){
    if(rendering)return;const c=findCard();if(!c)return;rendering=true;c.dataset.hashFastClaimed='1';
    if(!initialized||showLoading)c.innerHTML=`<div class="hash-head"><div><h3>Network Hash vs Pool Hash</h3><div class="muted small">Pool and Yerbas network hashrate over the selected time range.</div></div><div class="hash-range">${Object.keys(RANGES).map(k=>`<button type="button" disabled class="${k===selected?'active':''}">${k}</button>`).join('')}</div></div><div class="hash-loading">Loading hashrate history…</div>`;
    try{
      const data=await fetchData(selected),history=Array.isArray(data?.history)?data.history:[];if(!data||!history.length){if(!initialized)c.innerHTML='<h3>Network Hash vs Pool Hash</h3><div class="hash-loading">Waiting for hashrate data…</div>';return;}
      const networkNow=Number(data.network_hashrate||0),poolNow=Number(data.pool_hashrate||0),serverSamples=Array.isArray(data.network_history)?data.network_history:[],browserSamples=sampleNetwork(networkNow),samples=serverSamples.length?serverSamples:browserSamples,r=RANGES[selected],cut=Math.floor(Date.now()/1000)-r.hours*3600,rangeSamples=samples.filter(x=>Number(x.ts)>=cut),blocks=Array.isArray(data.pool_blocks)?data.pool_blocks:[];
      const ps=stats(history.map(x=>Number(x.hashrate||0))),ns=stats(history.map(x=>networkAt(rangeSamples,Number(x.ts||0),networkNow))),share=networkNow>0?poolNow/networkNow*100:0;
      c.innerHTML=`<div class="hash-head"><div><h3>Network Hash vs Pool Hash</h3><div class="muted small">Pool and Yerbas network hashrate over the selected time range.</div></div><div class="hash-range">${Object.keys(RANGES).map(k=>`<button type="button" data-range="${k}" class="${k===selected?'active':''}">${k}</button>`).join('')}</div></div><div class="hash-metrics"><div class="hash-metric"><span>Pool now</span><strong>${hashRate(poolNow)}</strong><small>${selected} average ${hashRate(ps.avg)}</small></div><div class="hash-metric"><span>Network now</span><strong>${hashRate(networkNow)}</strong><small>${selected} average ${hashRate(ns.avg)}</small></div><div class="hash-metric"><span>Pool share</span><strong>${share.toFixed(2)}%</strong><small>of current network hash</small></div><div class="hash-metric"><span>Peak pool</span><strong>${hashRate(ps.peak)}</strong><small>${selected} peak</small></div><div class="hash-metric"><span>Peak network</span><strong>${hashRate(ns.peak)}</strong><small>${selected} peak</small></div></div>${makeSvg(history,rangeSamples,networkNow,blocks)}<div class="hash-legend"><span><i class="hash-dot pool"></i>Pool hashrate</span><span><i class="hash-dot net"></i>Network hashrate</span><span><i class="hash-dot blocks"></i>Blocks found by pool</span></div><div class="hash-footer"><span>Left scale: pool hashrate · Right scale: network hashrate</span><span>${blocks.length} pool block${blocks.length===1?'':'s'} in range · Loaded ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span></div>`;
      bind(c,history,rangeSamples,networkNow,blocks);initialized=true;
    }finally{rendering=false;}
  }
  function start(){ensureStyles();const app=document.querySelector('main#app'),tryRender=()=>{if(findCard()){render();return true;}return false;};if(tryRender())return;if(app){const observer=new MutationObserver(()=>{if(tryRender()&&initialized)observer.disconnect();});observer.observe(app,{childList:true,subtree:true});}const fallback=setInterval(()=>{if(tryRender()&&initialized)clearInterval(fallback);},50);}
  start();
})();
